
[colors]
# primary = { background = "#000e1c" }

[window]
padding = { x = 5, y = 0 }
dynamic_padding = true
# opacity = 0.75
opacity = 0.8
decorations = "None"


[font]
size = 9.5
normal = { family = "MesloLGM Nerd Font" }

[keyboard]
bindings = [
{ key = "F11",  action = "ToggleFullScreen" },
# { key = "c", mods = "Control|Shift",  action = "CopySelection" },
]

[terminal]
# osc52 = "CopyPaste"

[general]
import = [
    "~/.config/alacritty/alacritty-theme/themes/papertheme.toml"
]
